
DELIMITER $
BEGIN NOT ATOMIC
	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.schemata WHERE schema_name = 'team') THEN
		SELECT 1 AS TeamSchemaExists;
	ELSE
		CREATE DATABASE team;
		GRANT ALL PRIVILEGES ON team.* TO scraper@'%' IDENTIFIED BY 'scraper';
		FLUSH PRIVILEGES;
	END IF;
END $
DELIMITER ;


USE team;

DELIMITER $
BEGIN NOT ATOMIC
	IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Team' AND TABLE_SCHEMA = 'team') THEN
		SELECT 1 AS TeamTableExists;
	ELSE
		CREATE TABLE Team
		(
				 
			
				 TeamID INT NOT NULL
				,TeamName VARCHAR(256) NOT NULL
			
				 
		
		);
	END IF; 
END $
DELIMITER ;
